version: "3"
services:
    worker:
        build:
            context: .
        volumes:
            - worker:/data
        stop_signal: SIGINT
        restart: unless-stopped
        command: "python -m hikka"
        ports:
            - "${EXTERNAL_PORT:-8080}:8080"
        deploy:
          resources:
            limits:
              cpus: '0.1'
              memory: 500M
            reservations:
              cpus: '0.01'
              memory: 200M

volumes:
    worker:
